
[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[character]
error_symbol = "[✖](bold red) "
success_symbol = "[➜](bold green)"

[username]
style_user = "bold dimmed blue"
show_always = false 

